create table tb_filme (id int8 generated by default as identity, count int4, imagem varchar(255), pontuacao float8, titulo varchar(255), primary key (id));
create table tb_pontuacao (valor float8, filme_id int8 not null, usuario_id int8 not null, primary key (filme_id, usuario_id));
create table tb_usuario (id int8 generated by default as identity, email varchar(255), primary key (id));
alter table if exists tb_pontuacao add constraint FKei91b58dw3rj7ecfao03jw0pl foreign key (filme_id) references tb_filme;
alter table if exists tb_pontuacao add constraint FKgcokptu3hlbyk9uvclrcnjad5 foreign key (usuario_id) references tb_usuario;
